### ISSUE TITLE
请问支持Element UI Plus / vue 3 吗？

### ISSUE THREAD

**Issue by sprklinginfo** [wangdaoo/el-filter#18]
正在写的项目是用Element UI Plus / vue 3， 不知道是否可以用这个插件。谢谢！

**Comment by wangdaoo** [comment]
嗯～。理论上3.x 是兼容 2.x 的，但是建议还是获取源码，根据自身需求重构一下。毕竟以后都是3.x

**Comment by huang-zp** [comment]
大佬加一个数字区间的搜索框吧

**Comment by wangdaoo** [comment]
@huang-zp 暂时可用插槽处理一下！
后期考虑使用 Vue3 + TS 重构
